import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./config.js";
const $=id=>document.getElementById(id); const message=$('adminMessage'), eventSelect=$('eventSelect'), tbody=$('attendanceBody'); let supabase=null,events=[],rows=[],selected=null;
const ready=SUPABASE_URL&&!SUPABASE_URL.includes('YOUR_')&&SUPABASE_ANON_KEY&&!SUPABASE_ANON_KEY.includes('YOUR_'); function msg(t='',type='info'){message.className=t?`message ${type}`:'message';message.textContent=t}
if(!ready)msg('Setup required: configure Supabase in config.js.','error');else{ supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); const {data:{session}}=await supabase.auth.getSession(); if(!session)location.replace('login.html'); else {const {data:ok}=await supabase.rpc('is_super_admin');if(!ok){await supabase.auth.signOut();location.replace('login.html?denied=1')}else loadAll();}}
async function loadAll(){msg('Loading…');const {data,error}=await supabase.from('events').select('*').order('event_date',{ascending:false}).order('created_at',{ascending:false});if(error){msg(error.message,'error');return}events=data||[];$('eventCount').textContent=events.length;renderSelect();msg('');if(events.length)await choose(eventSelect.value);else{selected=null;tbody.innerHTML='<tr class="empty-row"><td colspan="5">Create your first event above.</td></tr>';renderQR()}}
function renderSelect(){const prev=selected?.id;eventSelect.innerHTML=events.length?events.map(e=>`<option value="${e.id}">${esc(e.event_date)} · ${esc(e.name)}</option>`).join(''):'<option>No events yet</option>';if(prev&&events.some(e=>e.id===prev))eventSelect.value=prev}
async function choose(id){selected=events.find(e=>e.id===id)||events[0];if(!selected)return;eventSelect.value=selected.id;renderQR();const {data,error}=await supabase.from('attendance').select('id,student_name,batch_intake,team_name,checked_in_at').eq('event_id',selected.id).order('checked_in_at',{ascending:false}).limit(5000);if(error){msg(error.message,'error');return}rows=data||[];renderRows()}
function renderRows(){const q=$('searchInput').value.trim().toLowerCase();const f=rows.filter(r=>`${r.student_name} ${r.batch_intake} ${r.team_name}`.toLowerCase().includes(q));$('totalCount').textContent=rows.length;tbody.innerHTML=f.length?f.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.student_name)}</td><td>${esc(r.batch_intake)}</td><td>${esc(r.team_name||'—')}</td><td>${new Date(r.checked_in_at).toLocaleString()}</td></tr>`).join(''):'<tr class="empty-row"><td colspan="5">No attendance records found.</td></tr>'}
function renderQR(){const holder=$('qrCode');holder.innerHTML='';if(!selected){$('qrUrl').textContent='';$('eventStatus').textContent='No event selected';return}const url=new URL('./',location.href);url.searchParams.set('event',selected.slug);$('qrUrl').textContent=url.href;new QRCode(holder,{text:url.href,width:180,height:180,correctLevel:QRCode.CorrectLevel.H});const now=new Date(), open=selected.is_open&&(!selected.opens_at||now>=new Date(selected.opens_at))&&(!selected.closes_at||now<=new Date(selected.closes_at));$('eventStatus').textContent=`${selected.event_type} · ${selected.event_date} · ${open?'CHECK-IN OPEN':'CHECK-IN CLOSED'}`;$('toggleEventButton').textContent=selected.is_open?'Close Check-In':'Open Check-In'}
$('eventForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('newEventName').value.trim(),type=$('newEventType').value,date=$('newEventDate').value,opens=$('newOpensAt').value,closes=$('newClosesAt').value;if(opens&&closes&&new Date(closes)<=new Date(opens)){msg('Close time must be after open time.','error');return}const slug=`${slugify(name)}-${date.replaceAll('-','')}-${Math.random().toString(36).slice(2,6)}`.slice(0,80);const {data:{user}}=await supabase.auth.getUser();const payload={name,slug,event_type:type,event_date:date,opens_at:opens?new Date(opens).toISOString():null,closes_at:closes?new Date(closes).toISOString():null,require_team:$('newRequireTeam').checked,is_open:true,note:$('newNote').value.trim()||null,created_by:user.id};const {data,error}=await supabase.from('events').insert(payload).select().single();if(error){msg(error.message,'error');return}msg('Event created. Its unique QR is ready.','success');$('eventForm').reset();$('newEventDate').value=today();$('newRequireTeam').checked=type!=='Meeting';selected=data;await loadAll();eventSelect.value=data.id;await choose(data.id)});
$('newEventType').addEventListener('change',()=>{$('newRequireTeam').checked=$('newEventType').value!=='Meeting'});eventSelect.addEventListener('change',()=>choose(eventSelect.value));$('searchInput').addEventListener('input',renderRows);$('refreshButton').addEventListener('click',loadAll);$('logoutButton').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('login.html')});
$('toggleEventButton').addEventListener('click',async()=>{if(!selected)return;const {error}=await supabase.from('events').update({is_open:!selected.is_open}).eq('id',selected.id);if(error)return msg(error.message,'error');selected.is_open=!selected.is_open;const i=events.findIndex(e=>e.id===selected.id);events[i]=selected;renderQR();msg(`Check-in ${selected.is_open?'opened':'closed'} for ${selected.name}.`,'success')});
$('downloadQrButton').addEventListener('click',()=>{if(!selected)return;const h=$('qrCode'),c=h.querySelector('canvas'),im=h.querySelector('img'),u=c?c.toDataURL('image/png'):im?.src;if(!u)return;const a=document.createElement('a');a.href=u;a.download=`IMC-${slugify(selected.name)}-QR.png`;a.click()});
$('exportButton').addEventListener('click',()=>{if(!selected||!rows.length)return msg('No attendance to export for this event.','info');const csv=[['Student Name','Batch / Intake','Team Name','Check-in Time'],...rows.map(r=>[r.student_name,r.batch_intake,r.team_name,new Date(r.checked_in_at).toLocaleString()])].map(x=>x.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const u=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`${slugify(selected.name)}-attendance.csv`;a.click();URL.revokeObjectURL(u)});
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function slugify(v){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'event'}function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}$('newEventDate').value=today();
