import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./config.js";
const form=document.getElementById('checkinForm'), button=document.getElementById('checkinButton'), message=document.getElementById('message'), eventName=document.getElementById('eventName'), eventMeta=document.getElementById('eventMeta'), eventNote=document.getElementById('eventNote'), teamName=document.getElementById('teamName'), teamOptional=document.getElementById('teamOptional');
const slug=new URLSearchParams(location.search).get('event')?.toLowerCase().trim(); let currentEvent=null;
const ready=SUPABASE_URL&&!SUPABASE_URL.includes('YOUR_')&&SUPABASE_ANON_KEY&&!SUPABASE_ANON_KEY.includes('YOUR_'); const supabase=ready?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
function msg(t,type='info'){message.className=`message ${type}`;message.textContent=t}
if(!ready) msg('Setup required: configure Supabase in config.js.','error'); else if(!slug) msg('Invalid QR code. Please scan the QR for the current IMC event.','error'); else loadEvent();
async function loadEvent(){const {data,error}=await supabase.rpc('get_public_event',{p_slug:slug}); const e=Array.isArray(data)?data[0]:data; if(error||!e){eventName.textContent='Event not found';msg('This event link is invalid. Please ask an organizer for the current QR code.','error');return} currentEvent=e; eventName.textContent=e.name; document.title=`${e.name} · IMC Attendance`; eventMeta.textContent=`${e.event_type} · ${formatDate(e.event_date)}`; eventNote.textContent=e.note||''; teamName.required=e.require_team; teamOptional.textContent=e.require_team?'':'(Optional)'; if(e.accepting_checkins){form.hidden=false;msg('Check-in is open.','success')} else {form.hidden=true; if(!e.is_open) msg('Check-in is closed for this event.','error'); else if(e.opens_at&&new Date()<new Date(e.opens_at)) msg(`Check-in opens at ${formatDateTime(e.opens_at)}.`,'info'); else msg('Check-in is closed for this event.','error')}}
form.addEventListener('submit',async ev=>{ev.preventDefault();if(!supabase||!currentEvent)return;const name=document.getElementById('studentName').value.trim(),batch=document.getElementById('batchIntake').value.trim(),team=teamName.value.trim();if(!name||!batch||(currentEvent.require_team&&!team)){msg('Please fill in all required fields.','error');return}button.disabled=true;button.classList.add('loading');msg('Checking you in…');const {data,error}=await supabase.rpc('check_in_event',{p_event_slug:slug,p_student_name:name,p_batch_intake:batch,p_team_name:team});button.disabled=false;button.classList.remove('loading');if(error){console.error(error);msg('Check-in failed. Please contact an organizer.','error');return}if(data?.status==='success'){msg(`✓ Check-in successful. Welcome, ${name}!`,'success');form.reset()}else if(data?.status==='duplicate')msg('You are already checked in for this event.','info');else if(data?.status==='not_open_yet')msg(`Check-in opens at ${formatDateTime(data.opens_at)}.`,'info');else msg('Check-in is closed for this event.','error')});
function formatDate(v){return new Date(`${v}T00:00:00`).toLocaleDateString([],{year:'numeric',month:'short',day:'numeric'})} function formatDateTime(v){return new Date(v).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
